In [25]:
import yfinance as yf
import pandas as pd
import numpy as np
import xlwings as xw
import datetime as dt

In [26]:
def write_xl():
    """
    Args:
        tickers (list of str): 
    """
    wb = xw.Book.caller()
    sheet0 = wb.Sheets[0]
    
    ticker = sheet0["A2"]
    start_date = pd.to_datetime(sheet0["B2"], format=sheet0["D2"])
    end_date = pd.to_datetime(sheet0["C2"], format=sheet0["D2"])
    
    data = yf.download(ticker, start_date, end_date)
    wb.sheets[0].range("A5").value = data

In [27]:
tickers = ["MSFT", "TSLA", "AAPL"]

# start_date = "01.01.2024"
# end_date = "01.02.2024"

start_date = "2024/01/01"
end_date = "2024/02/01"

write_xl(tickers, start_date, end_date, date_format="%Y/%m/%d")

[*********************100%%**********************]  3 of 3 completed

Price        Adj Close                               Close              \
Ticker            AAPL        MSFT        TSLA        AAPL        MSFT
Date
2024-01-02  185.403412  370.185425  248.419998  185.639999  370.869995
2024-01-03  184.015198  369.915924  238.449997  184.250000  370.600006
2024-01-04  181.678177  367.260834  237.929993  181.910004  367.940002
2024-01-05  180.949097  367.071198  237.490005  181.179993  367.750000
2024-01-08  185.323517  373.998383  240.449997  185.559998  374.690002
2024-01-09  184.904053  375.096375  234.960007  185.139999  375.790009
2024-01-10  185.952713  382.063446  233.940002  186.190002  382.769989
2024-01-11  185.353485  383.920044  227.220001  185.589996  384.630005
2024-01-12  185.683060  387.752960  218.889999  185.919998  388.470001
2024-01-16  183.395981  389.549622  219.910004  183.630005  390.269989
2024-01-17  182.447189  388.751099  215.550003  182.679993  389.470001
2024-01-18  188.389618  393.142975  211.880005  188.630005  393.869995
2024-01-19  191.315872  397.934143  212.190002  191.559998  398.670013
2024-01-22  193.642899  395.778107  208.800003  193.889999  396.510010
2024-01-23  194.931259  398.163696  209.139999  195.179993  398.899994
2024-01-24  194.252121  401.816925  207.830002  194.500000  402.559998
2024-01-25  193.922546  404.122681  182.630005  194.169998  404.869995
2024-01-26  192.174774  403.184418  183.250000  192.419998  403.929993
2024-01-29  191.485657  408.963715  190.929993  191.729996  409.720001
2024-01-30  187.800354  407.835815  191.589996  188.039993  408.589996
2024-01-31  184.164993  396.846130  187.289993  184.399994  397.579987

Price                         High                                 Low  \
Ticker            TSLA        AAPL        MSFT        TSLA        AAPL
Date
2024-01-02  248.419998  188.440002  375.899994  251.250000  183.889999
2024-01-03  238.449997  185.880005  373.260010  245.679993  183.429993
2024-01-04  237.929993  183.089996  373.100006  242.699997  180.880005
2024-01-05  237.490005  182.759995  372.059998  240.119995  180.169998
2024-01-08  240.449997  185.600006  375.200012  241.250000  181.500000
2024-01-09  234.960007  185.149994  375.989990  238.960007  182.729996
2024-01-10  233.940002  186.399994  384.170013  235.500000  183.919998
2024-01-11  227.220001  187.050003  390.679993  230.929993  183.619995
2024-01-12  218.889999  186.740005  388.679993  225.339996  185.190002
2024-01-16  219.910004  184.259995  394.029999  223.490005  180.929993
2024-01-17  215.550003  182.929993  390.109985  215.669998  180.300003
2024-01-18  211.880005  189.139999  393.989990  217.449997  185.830002
2024-01-19  212.190002  191.949997  398.670013  213.190002  188.820007
2024-01-22  208.800003  195.330002  400.619995  217.800003  192.259995
2024-01-23  209.139999  195.750000  399.380005  215.649994  193.830002
2024-01-24  207.830002  196.380005  405.630005  212.729996  194.339996
2024-01-25  182.630005  196.270004  407.010010  193.000000  193.110001
2024-01-26  183.250000  194.759995  406.170013  186.779999  191.940002
2024-01-29  190.929993  192.199997  409.980011  191.479996  189.580002
2024-01-30  191.589996  191.800003  413.049988  196.360001  187.470001
2024-01-31  187.289993  187.100006  415.320007  193.970001  184.350006

Price                                     Open                          \
Ticker            MSFT        TSLA        AAPL        MSFT        TSLA
Date
2024-01-02  366.769989  244.410004  187.149994  373.859985  250.080002
2024-01-03  368.510010  236.320007  184.220001  369.010010  244.979996
2024-01-04  367.170013  237.729996  182.149994  370.670013  239.250000
2024-01-05  366.500000  234.899994  181.990005  368.970001  236.860001
2024-01-08  369.010010  235.300003  182.089996  369.299988  236.139999
2024-01-09  371.190002  232.039993  183.919998  372.010010  238.110001
2024-01-10  376.320007  231.289993  184.350006  376.369995  235.100006
2024-01-11  380.380005  225.369995  186.539993  386.000000  230.570007
2024-01-12  384.649994  217.149994  186.059998  385.489990  220.080002
2024-01-16  387.619995  212.179993  182.160004  393.660004  215.100006
2024-01-17  384.809998  212.009995  181.270004  387.980011  214.860001
2024-01-18  390.119995  208.740005  186.089996  391.720001  216.880005
2024-01-19  393.500000  207.559998  189.330002  395.760010  209.990005
2024-01-22  393.589996  206.270004  192.300003  400.019989  212.259995
2024-01-23  393.929993  207.750000  195.020004  395.750000  211.300003
2024-01-24  400.450012  206.770004  195.419998  401.540009  211.880005
2024-01-25  402.529999  180.059998  195.220001  404.320007  189.699997
2024-01-26  402.429993  182.100006  194.270004  404.369995  185.500000
2024-01-29  404.329987  183.669998  192.009995  406.059998  185.630005
2024-01-30  406.450012  190.610001  190.940002  412.260010  195.330002
2024-01-31  397.209991  185.850006  187.039993  406.959991  187.000000

Price         Volume
Ticker          AAPL      MSFT       TSLA
Date
2024-01-02  82488700  25258600  104654200
2024-01-03  58414500  23083500  121082600
2024-01-04  71983600  20901500  102629300
2024-01-05  62303300  20987000   92379400
2024-01-08  59144500  23134000   85166600
2024-01-09  42841800  20830000   96705700
2024-01-10  46792900  25514200   91628500
2024-01-11  49128400  27850800  105873600
2024-01-12  40444700  21645700  122889000
2024-01-16  65603000  27202300  115355000
2024-01-17  47317400  22234100  103164400
2024-01-18  78005800  23392100  108595400
2024-01-19  68741000  29272000  102095800
2024-01-22  60133900  27016900  117952500
2024-01-23  42355600  20525900  106605900
2024-01-24  53631300  24867000  123369900
2024-01-25  54822100  21021200  198076800
2024-01-26  44594000  17803300  107343200
2024-01-29  47145600  24510200  125013100
2024-01-30  55859400  33477600  109982300
2024-01-31  55467800  47871100  103221400

In [28]:
yf.download("TSLA", period="1mo")

[*********************100%%**********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2024-03-04,198.729996,199.750000,186.720001,188.139999,188.139999,134334900
2024-03-05,183.050003,184.589996,177.570007,180.740005,180.740005,119660800
2024-03-06,179.990005,181.580002,173.699997,176.539993,176.539993,107920900
2024-03-07,174.350006,180.039993,173.699997,178.649994,178.649994,102129000
2024-03-08,181.500000,182.729996,174.699997,175.339996,175.339996,85315300
2024-03-11,175.449997,182.869995,174.800003,177.770004,177.770004,85391500
2024-03-12,177.770004,179.429993,172.410004,177.539993,177.539993,87391700
2024-03-13,173.050003,176.050003,169.149994,169.479996,169.479996,106524500
2024-03-14,167.770004,171.169998,160.509995,162.500000,162.500000,126325700
2024-03-15,163.160004,165.179993,160.759995,163.570007,163.570007,96971900
2024-03-18,170.020004,174.720001,165.899994,173.800003,173.800003,108214400
2024-03-19,172.360001,172.820007,167.419998,171.320007,171.320007,77271400
2024-03-20,173.000000,176.250000,170.820007,175.660004,175.660004,83846700
2024-03-21,176.389999,178.179993,171.800003,172.820007,172.820007,73178000
2024-03-22,166.690002,171.199997,166.300003,170.830002,170.830002,75454700
2024-03-25,168.759995,175.240005,168.729996,172.630005,172.630005,74228600
2024-03-26,178.580002,184.250000,177.380005,177.669998,177.669998,113186200
2024-03-27,181.410004,181.910004,176.000000,179.830002,179.830002,81804000
2024-03-28,177.449997,179.570007,175.300003,175.789993,175.789993,77654800
2024-04-01,176.169998,176.750000,170.210007,175.220001,175.220001,81562100
2024-04-02,164.750000,167.690002,163.429993,166.630005,166.630005,116650600
2024-04-03,164.020004,168.820007,163.279999,168.380005,168.380005,82578000

In [ ]:
"F_Cotton" - "F_"